name: Deployment

on:
  push:
    branches: [ "release/dev", "release/live" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/release/live' && 'live' || 'dev' }}
    container:
      image: node:alpine3.19
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/release/live' && 'live' || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - name: Cacheing
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          echo "Building for [${ENVIRONMENT}] mode"
          npm run build:${ENVIRONMENT}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/

  deployment:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.ref == 'refs/heads/release/live' && 'live' || 'dev' }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deployment
        run: |
          BUCKET_NAME=${{ vars.DEPLOY_BUCKET_NAME }}
          CLOUDFRONT_DISTRIBUTION_ID=${{ vars.CLOUDFRONT_DISTRIBUTION_ID}}
          echo "BUCKET_NAME = ${BUCKET_NAME}"
          echo "CLOUDFRONT_DISTRIBUTION_ID = ${CLOUDFRONT_DISTRIBUTION_ID}"
          aws s3 sync dist/ s3://$BUCKET_NAME
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

        
    
